//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Museum1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuseumEntities : DbContext
    {
        public MuseumEntities()
            : base("name=MuseumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Excursion> Excursion { get; set; }
        public virtual DbSet<Exhibit> Exhibit { get; set; }
        public virtual DbSet<Guide> Guide { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
